disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- trailing_newline

excluded: # paths to ignore during linting. Takes precedence over `included`.
- VendingMachineApp/BeverageTests/.
- Pods

line_length:
warning: 99
error: 120

